version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/image-classifier:/app  # Для hot-reload у розробці

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/image-classifier-web/src:/app/src
    depends_on:
      - backend